### ISSUE TITLE
emancipate from upstream repo ?

### ISSUE THREAD

**Issue by hannesa2** [bitcoincash-wallet/bitcoincash-wallet#1]
I want to make a PR here, but I can't because it's a fork. 
When you have no plane to merge/rebase from upstream I recommend to emancipate from it and disconnect from it.
To be honest, I guess it makes no sense to merge/rebase from upstream.

**Comment by HashEngineering** [comment]
It makes a lot of sense to merge from upstream.  Bitcoin Wallet is continually updated with bug fixes and we have merged at least once to pull these updates to make a better app.  We plan to do so in the future as well.

Why can't you submit a PR?  Whether this repo is a fork or not on GitHub of Bitcoin Wallet shouldn't matter.

**Comment by hannesa2** [comment]
in upstream repo I measured some missing commits, and this guy publish something which is not in github repo. This is a **no-go** , so I try to change this with an [PR](https://github.com/bitcoin-wallet/bitcoin-wallet/pull/459) but this guy only accept changes which changes the README.md
So I go my own way, providing a deterministic build to increase trust

<img width="380" alt="image" src="https://user-images.githubusercontent.com/3314607/34493480-604e0752-efec-11e7-995f-ff213d7dc6a2.png">

So I want to have this in _Bitcoin cash_ wallet as well and I want to see, if you keep close to upstream, or want some improvement eg
* remove Eclipse structure
* update to most recent Android Studio
* deterministic build 
* network usage
... which makes rebase probably harder
 
Ok, it was my idea as I saw your last merge was `5.39`, it means you are behind and skip currently `5.40` `5.41` `5.42`
So the main question for me is, if I support you with PR's or go immediate my own way.

I see you stay close to upstream, if you want to change this just write in this issue

**Comment by HashEngineering** [comment]
We don't merge from upstream every time an update comes out, rather every 10 updates or so we pull the updates.  The deterministic build seems interesting. 

remove Eclipse structure - I would not do this, in case some users do want to use Eclipse
update to most recent Android Studio - This I wouldn't do as I am afraid it may break some of the build process.  It would be worth testing though.
deterministic build - This is very interesting
network usage - not sure what this is.

These changes make merging a bit harder, but doable.

**Comment by hannesa2** [comment]
remove Eclipse
pro:
* upstream use always a `v5.xx-prod` branch to archive a prod release. For this are **flavors** designed, but you can't use flavors with Eclipse stucture

contra:
* "users do want to use Eclipse" (at least I can't build with Eclipse any more. It's not unsupported anymore since Sep'16
* compatible to upstream
