### ISSUE TITLE
prevent multidex ?

### ISSUE THREAD

**Issue by hannesa2** [bitcoincash-wallet/bitcoincash-wallet#18]
https://github.com/bitcoincash-wallet/bitcoincash-wallet/blob/dfcae370af67a96ddd4ae00a6fa16afb8865762f/wallet/build.gradle#L54

It should use `release` here

I know the owner of the upstream repo is resistant to improvements, but it seam this is an ugly workaround to prevent from multidex issues. 
Independent of this proguard has an issue with PR https://github.com/bitcoincash-wallet/bitcoincash-wallet/pull/4

**Comment by hannesa2** [comment]
btw, I gave up to try to help the upstream repo owner

**Comment by HashEngineering** [comment]
What are the multidex issues that need to be worked around?

**Comment by hannesa2** [comment]
When I use here `release` (means `debug` without proguard) I run into multidex issues.
Why ?
When you do not proguard , then all useless dependencies eg, `bitcoincashj-examples` `wallettemplate` are included and not removed. (I think) this causes the multidex issue, please see https://github.com/bitcoincash-wallet/bitcoincash-wallet/pull/4
