### ISSUE TITLE
Failing to resolve bitcoincashj dependency.

### ISSUE THREAD

**Issue by snapfractalpop** [bitcoincash-wallet/bitcoincash-wallet#5]
I'm building in Android Studio, and the gradle dependency is not resolving, so I'm getting the following error:

> Error:(18, 13) Failed to resolve: org.bitcoincashj:bitcoincashj-core:0.14.5

The dependency is specified in the file "wallet/build.gradle":
`compile 'org.bitcoincashj:bitcoincashj-core:0.14.5'`

Has the dependency changed, or does it possibly have a typo?

**Comment by HashEngineering** [comment]
I didn't have `org.bitcoincashj:bitcoincashj-core:0.14.5` uploaded to an online repository, such as jcenter or maven.  I had it built locally using maven.

I am no longer supporting my bitcoincashj, but have moved to bitcoinj-cash - https://github.com/bitcoinj-cash/bitcoinj.  My next version of this app will use bitcoinj-cash once that is updated to include some bug fixes and adds the cash-address format.

**Comment by snapfractalpop** [comment]
Thanks for the fast response! Do you know if there is a jcenter or maven repository for the bitcoinj-cash library that you are moving to? Or do you recommend that I build the older version locally for now?

**Comment by HashEngineering** [comment]
Yes, the current version is 0.14.5.2 on maven.

compile 'cash.bitcoinj:bitcoinj-core:0.14.5.2'

**Comment by snapfractalpop** [comment]
Thanks! I'm closing this now.
