### ISSUE TITLE
Roadmap or todo list?

### ISSUE THREAD

**Issue by snapfractalpop** [bitcoincash-wallet/bitcoincash-wallet#8]
I am interested in contributing to this project. I have successfully compiled the wallet apk after resolving the dependency issue from here #5. Is there a roadmap or todo list, or any assigned tasks that can avoid duplication of effort on this project?

**Comment by HashEngineering** [comment]
I created a project under this wiki for what is called the Version 6 upgrade.
https://github.com/bitcoincash-wallet/bitcoincash-wallet/projects/1

We also have pull requests to review and other issues.

**Comment by snapfractalpop** [comment]
Thanks. I will see what I can do to help the project.
